@extends('legal.layout')

@section('title', 'Privacy Policy')
@section('legal-heading', 'Privacy Policy')

@section('legal-content')

    <p>This policy explains what the EciattoLife mobile app and web system collect about you, why, how long it is kept, and how to have it deleted. It applies to the EciattoLife Android and iOS apps and to <strong>life.eciatto.com</strong>.</p>

    <h2>1. Who this applies to</h2>

    <p>EciattoLife is a workforce and CRM system used by businesses to manage their staff, tasks, leads and forms. You cannot sign up for it yourself — accounts are created for you by your employer, who decides what data is collected and who can see it.</p>

    <p>That means your <strong>employer</strong> controls the personal data in EciattoLife, and Eciatto operates the system on their behalf. If you want your data corrected or removed, you can contact either of us, but your employer may need to authorise it.</p>

    <h2>2. What we collect and why</h2>

    <table class="legal-table">
        <thead>
            <tr>
                <th style="width: 30%;">Data</th>
                <th style="width: 40%;">Why</th>
                <th style="width: 30%;">Source</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Name, username, email address, mobile number, gender</td>
                <td>To identify you, sign you in, assign work to you, and let colleagues contact you</td>
                <td>Entered by your employer when your account is created</td>
            </tr>
            <tr>
                <td><strong>Precise location, including in the background</strong></td>
                <td>To record where a task check-in happened, as required by your employer</td>
                <td>Your device — see section 3</td>
            </tr>
            <tr>
                <td>Photos and documents you upload</td>
                <td>Attachments and evidence on tasks, leads, inspection reports and form submissions</td>
                <td>Your camera or photo library, when you choose to attach something</td>
            </tr>
            <tr>
                <td>Push notification token (Firebase Cloud Messaging)</td>
                <td>To send you notifications about tasks, approvals and check-in requests</td>
                <td>Generated by Google on your device when you install the app</td>
            </tr>
            <tr>
                <td>Work records — tasks, leads, inspection reports, form submissions, comments, ratings, bookings</td>
                <td>These are your employer's business records of work performed</td>
                <td>Created as you use the app</td>
            </tr>
            <tr>
                <td>Sign-in times and app version</td>
                <td>Account security and support</td>
                <td>Recorded automatically</td>
            </tr>
            <tr>
                <td>Error diagnostics — the screen name, error message and the input involved when something goes wrong</td>
                <td>To find and fix crashes and bugs</td>
                <td>Sent automatically by the app when an error occurs</td>
            </tr>
            <tr>
                <td>Telegram chat ID and calendar booking details, where your employer has enabled those integrations</td>
                <td>To deliver notifications via Telegram and to manage appointment bookings</td>
                <td>Configured by your employer</td>
            </tr>
        </tbody>
    </table>

    <p>We do not sell your personal data, and we do not use it for advertising or to build advertising profiles.</p>

    <h2>3. Location, including background collection</h2>

    <div class="legal-callout">
        <p><strong>EciattoLife collects your precise GPS location, and it can do so while the app is closed or not in use.</strong> This happens when your employer requests a task check-in.</p>
    </div>

    <p>In detail:</p>

    <ul>
        <li>Location is captured <strong>in response to a check-in request</strong> tied to a task — not continuously, and not as a general movement trail.</li>
        <li>If you have granted the "Allow all the time" background location permission, a check-in can be recorded <strong>even when the app is closed or running in the background</strong>. This is why the app requests that permission.</li>
        <li>Your device shows you a notification <strong>every time</strong> a location is recorded, so a check-in never happens silently.</li>
        <li>Each record contains the latitude and longitude, the time, and the task it relates to. It is sent to your employer and is visible to managers in the EciattoLife web system.</li>
        <li>You can see the current setting, and change or withdraw the permission at any time, under <strong>More &rarr; Privacy &rarr; Location check-ins</strong> in the app, or in your device settings. Withdrawing it stops background collection; your employer may still require check-ins to be completed while the app is open.</li>
    </ul>

    <p>Location data is not used for any purpose other than recording task check-ins for your employer.</p>

    <h2>4. Camera, photos and files</h2>

    <p>The app asks for camera and photo library access only so you can attach a photo or document to a task, lead, report or form. It does not scan, index or upload anything from your device that you have not chosen to attach.</p>

    <h2>5. Push notifications</h2>

    <p>The app registers a Firebase Cloud Messaging token with Google so that we can send notifications to your device. That token identifies the app installation, not you personally, but we store it against your account so notifications reach the right person. You can turn notifications off in your device settings at any time.</p>

    <h2>6. Who your data is shared with</h2>

    <ul>
        <li><strong>Your employer</strong> — managers and administrators at your organisation can see your profile, your work records, your uploads and your task check-in locations. This is the purpose of the system.</li>
        <li><strong>Google (Firebase Cloud Messaging)</strong> — to deliver push notifications.</li>
        <li><strong>Amazon Web Services</strong> — photos and documents are stored in Amazon S3 in the Asia Pacific (Singapore) region.</li>
        <li><strong>Telegram</strong> — only if your employer has enabled Telegram notifications for your account.</li>
        <li><strong>Cal.com</strong> — only if your employer uses the calendar booking integration.</li>
        <li><strong>Authorities</strong> — where we are legally required to disclose data.</li>
    </ul>

    <p>We do not share your personal data with anyone else.</p>

    <h2>7. Where your data is stored</h2>

    <p>Account and work records are stored on our servers. Uploaded photos and documents are stored in Amazon S3 in the Asia Pacific (Singapore) region. Data is transmitted over encrypted HTTPS connections, and your sign-in token is held in your device's secure storage.</p>

    <h2>8. How long we keep it</h2>

    <ul>
        <li><strong>While your account is active</strong>, your profile, location check-ins, uploads and work records are retained so the system can function and your employer can refer back to them.</li>
        <li><strong>When you request deletion</strong> (see section 9), your account is disabled immediately, and we erase your personal data — your name, email, mobile number, location history, uploads and push token — within 30 days of verifying the request.</li>
        <li><strong>Records of work performed</strong> — tasks, leads, reports and form submissions — are retained after that as your employer's business records, with your identifying details removed.</li>
        <li>We may keep data longer where the law requires it, or where it is needed to resolve a dispute.</li>
    </ul>

    <h2>9. Deleting your account and data</h2>

    <p>You can request deletion in either of these ways:</p>

    <ul>
        <li><strong>In the app:</strong> go to <strong>More &rarr; Account &rarr; Delete Account</strong>. Your account is disabled straight away and you are signed out; you will not be able to sign in again.</li>
        <li><strong>On the web, without the app:</strong> use the form at <a href="{{ route('legal.accountDeletion') }}">{{ route('legal.accountDeletion') }}</a>.</li>
    </ul>

    <p>Either route notifies our team. We verify the request and then erase your personal data within 30 days, keeping only the anonymised work records described in section 8. You can also email us directly at <a href="mailto:{{ config('mail.deletion_notify_address') }}">{{ config('mail.deletion_notify_address') }}</a>.</p>

    <p>Because EciattoLife accounts belong to your employer, we may need to confirm the request with them before erasing data — for example where records are subject to your employment terms or to a legal retention requirement.</p>

    <h2>10. Your rights</h2>

    <p>Under Malaysia's Personal Data Protection Act 2010 and comparable laws elsewhere, you can ask to access the personal data we hold about you, correct it if it is wrong, limit how it is processed, or have it deleted. Contact us using the details in section 13, and we will respond within 30 days. Since your employer controls this data, we may refer your request to them.</p>

    <h2>11. Security</h2>

    <p>Access to EciattoLife requires a password, and sessions are token-based and can be revoked. Data travels over encrypted connections, and access within your organisation is restricted by role. No system is perfectly secure, but we take reasonable steps to protect your data against loss and unauthorised access.</p>

    <h2>12. Children</h2>

    <p>EciattoLife is a workplace tool for employees. It is not directed at children and we do not knowingly collect data from anyone under 18.</p>

    <h2>13. Changes and contact</h2>

    <p>If we change this policy we will update the date at the top of this page, and we will tell you in the app if the change is significant.</p>

    <p>Questions about this policy, or about your data:</p>

    <ul>
        <li>Email: <a href="mailto:{{ config('mail.deletion_notify_address') }}">{{ config('mail.deletion_notify_address') }}</a></li>
        <li>Web: <a href="{{ url('/') }}">{{ url('/') }}</a></li>
    </ul>

@endsection
