@extends('legal.layout')

@section('title', 'Privacy Policy')
@section('legal-heading', 'Privacy Policy')

@section('legal-content')

    <p>This policy explains what the Ronda mobile app and web system collect about you, why, how long it is kept, and how to have it deleted. It applies to the Ronda Android and iOS apps and to <strong>hq.ronda.asia</strong>.</p>

    <h2>1. Who this applies to</h2>

    <p>Ronda is a field sales and service system that businesses use to manage their staff, outlet visits, tasks, orders and forms. You cannot sign up for it yourself — accounts are created for you by your employer, who decides what data is collected and who can see it.</p>

    <p>That means your <strong>employer</strong> controls the personal data in Ronda, and we at Ronda run the system on their behalf. If you want your data corrected or removed, you can contact either of us, but your employer may need to authorise it.</p>

    <h2>2. What we collect and why</h2>

    <table class="legal-table">
        <thead>
            <tr>
                <th style="width: 30%;">Data</th>
                <th style="width: 40%;">Why</th>
                <th style="width: 30%;">Source</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Name, username, email address, mobile number, gender</td>
                <td>To identify you, sign you in, assign work to you, and let colleagues contact you</td>
                <td>Entered by your employer when your account is created</td>
            </tr>
            <tr>
                <td><strong>Location Stamps</strong> — your precise location, recorded only when you submit a form that asks for it or stamp an outlet's location</td>
                <td>To show where a form was completed, and where an outlet is</td>
                <td>Your device — see section 3</td>
            </tr>
            <tr>
                <td>Photos and documents you upload</td>
                <td>Attachments and evidence on tasks, outlets, visit reports and form submissions</td>
                <td>Your camera or photo library, when you choose to attach something</td>
            </tr>
            <tr>
                <td>Push notification token (Firebase Cloud Messaging)</td>
                <td>To send you notifications about tasks, approvals and form steps waiting for you</td>
                <td>Generated by Google on your device when you install the app</td>
            </tr>
            <tr>
                <td>Work records — tasks, outlets and their orders, visit reports, form submissions, comments and ratings</td>
                <td>These are your employer's business records of work performed</td>
                <td>Created as you use the app</td>
            </tr>
            <tr>
                <td>Sign-in times</td>
                <td>Account security and support</td>
                <td>Recorded automatically</td>
            </tr>
            <tr>
                <td>Error diagnostics — the screen name, error message and the input involved when something goes wrong</td>
                <td>To find and fix crashes and bugs</td>
                <td>Sent automatically by the app when an error occurs</td>
            </tr>
            <tr>
                <td>Telegram chat ID, where your employer has enabled Telegram notifications</td>
                <td>To deliver notifications via Telegram</td>
                <td>Configured by your employer</td>
            </tr>
        </tbody>
    </table>

    <p>We do not sell your personal data, and we do not use it for advertising or to build advertising profiles.</p>

    <h2>3. Location</h2>

    <div class="legal-callout">
        <p><strong>Ronda records your location only when you submit a form that asks for it, or when you stamp an outlet's location.</strong> It never records your location in the background or while the app is closed, and it does not follow your movements.</p>
    </div>

    <p>In detail:</p>

    <ul>
        <li><strong>Forms:</strong> some forms include a <strong>Location Stamp</strong> field. Depending on how your employer set up the form, your device reads its location when the form opens or when you tap <strong>Stamp location</strong>. The location is saved <strong>only when you submit the form</strong>. If you leave the form without submitting it, nothing is saved.</li>
        <li><strong>Outlets:</strong> on an outlet's page you can tap <strong>Stamp location</strong> to save where the outlet is. This happens only when you tap the button.</li>
        <li>Each stamp contains the latitude and longitude, the accuracy your device reports, and the time. It is saved with the form or outlet it belongs to, and your managers can see it in Ronda HQ.</li>
        <li>The location always comes from your device. It cannot be typed in; it can only be replaced by taking a new stamp.</li>
        <li>Ronda asks for location access only while you are using it. You can withdraw the permission at any time in your device or browser settings. You will then not be able to submit forms that require a Location Stamp, but the rest of Ronda keeps working.</li>
    </ul>

    <p>Location data is used only for these stamps. It is not used for anything else.</p>

    <h2>4. Camera, photos and files</h2>

    <p>The app asks for camera and photo library access only so you can attach a photo or document to a task, outlet, report or form. It does not scan, index or upload anything from your device that you have not chosen to attach.</p>

    <h2>5. Push notifications</h2>

    <p>The app registers a Firebase Cloud Messaging token with Google so that we can send notifications to your device. That token identifies the app installation, not you personally, but we store it against your account so notifications reach the right person. You can turn notifications off in your device settings at any time.</p>

    <h2>6. Who your data is shared with</h2>

    <ul>
        <li><strong>Your employer</strong> — managers and administrators at your organisation can see your profile, your work records, your uploads and the Location Stamps on your forms and outlets. This is the purpose of the system.</li>
        <li><strong>Google (Firebase Cloud Messaging)</strong> — to deliver push notifications.</li>
        <li><strong>Amazon Web Services</strong> — photos and documents are stored in Amazon S3 in the Asia Pacific (Singapore) region.</li>
        <li><strong>Amazon Web Services (Amazon Bedrock)</strong> — only if your employer has turned on Ronda's AI features. To write the Morning Round-Up for managers, Ronda sends a summary of the team's work: staff names, task titles, outlet names, and counts of tasks, visits, forms and orders. To explain Suggested Orders, it sends the outlet's type, size and segment and product figures. AWS states that Amazon Bedrock does not use this data to train AI models.</li>
        <li><strong>Telegram</strong> — only if your employer has enabled Telegram notifications for your account.</li>
        <li><strong>Authorities</strong> — where we are legally required to disclose data.</li>
    </ul>

    <p>We do not share your personal data with anyone else.</p>

    <h2>7. Where your data is stored</h2>

    <p>Account and work records are stored on our servers. Uploaded photos and documents are stored in Amazon S3 in the Asia Pacific (Singapore) region. When the AI features are on, the summaries described in section 6 are processed by Amazon Bedrock in the AWS region we configure for Ronda. Data is transmitted over encrypted HTTPS connections, and your sign-in token is held in your device's secure storage.</p>

    <h2>8. How long we keep it</h2>

    <ul>
        <li><strong>While your account is active</strong>, your profile, uploads and work records — including the Location Stamps on them — are retained so the system can function and your employer can refer back to them.</li>
        <li><strong>When you request deletion</strong> (see section 9), your account is disabled immediately, and we erase your personal data — your name, email, mobile number, uploads and push token — within 30 days of verifying the request.</li>
        <li><strong>Records of work performed</strong> — tasks, outlets and orders, visit reports and form submissions, including the Location Stamps on them — are retained after that as your employer's business records, with your identifying details removed.</li>
        <li>We may keep data longer where the law requires it, or where it is needed to resolve a dispute.</li>
    </ul>

    <h2>9. Deleting your account and data</h2>

    <p>You can request deletion in either of these ways:</p>

    <ul>
        <li><strong>In the app:</strong> go to <strong>More &rarr; Account &rarr; Delete Account</strong>. Your account is disabled straight away and you are signed out; you will not be able to sign in again.</li>
        <li><strong>On the web, without the app:</strong> use the form at <a href="{{ route('legal.accountDeletion') }}">{{ route('legal.accountDeletion') }}</a>.</li>
    </ul>

    <p>Either route notifies our team. We verify the request and then erase your personal data within 30 days, keeping only the anonymised work records described in section 8. You can also email us directly at <a href="mailto:{{ config('mail.deletion_notify_address') }}">{{ config('mail.deletion_notify_address') }}</a>.</p>

    <p>Because Ronda accounts belong to your employer, we may need to confirm the request with them before erasing data — for example where records are subject to your employment terms or to a legal retention requirement.</p>

    <h2>10. Your rights</h2>

    <p>Under Malaysia's Personal Data Protection Act 2010 and comparable laws elsewhere, you can ask to access the personal data we hold about you, correct it if it is wrong, limit how it is processed, or have it deleted. Contact us using the details in section 13, and we will respond within 30 days. Since your employer controls this data, we may refer your request to them.</p>

    <h2>11. Security</h2>

    <p>Access to Ronda requires a password, and sessions are token-based and can be revoked. Data travels over encrypted connections, and access within your organisation is restricted by role. No system is perfectly secure, but we take reasonable steps to protect your data against loss and unauthorised access.</p>

    <h2>12. Children</h2>

    <p>Ronda is a workplace tool for employees. It is not directed at children and we do not knowingly collect data from anyone under 18.</p>

    <h2>13. Changes and contact</h2>

    <p>If we change this policy we will update the date at the top of this page, and we will tell you in the app if the change is significant.</p>

    <p>Questions about this policy, or about your data:</p>

    <ul>
        <li>Email: <a href="mailto:{{ config('mail.deletion_notify_address') }}">{{ config('mail.deletion_notify_address') }}</a></li>
        <li>Web: <a href="{{ url('/') }}">{{ url('/') }}</a></li>
    </ul>

@endsection
